name: Merge Title Enforcer

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  enforce-merge-title:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Template
        id: check-template
        run: |
          PATCH=$(grep '\- \[x\] Patch' $GITHUB_EVENT_PATH)
          MINOR=$(grep '\- \[x\] Minor' $GITHUB_EVENT_PATH)
          MAJOR=$(grep '\- \[x\] Major' $GITHUB_EVENT_PATH)
          
          if [ -n "$PATCH" ]; then
            echo "::set-output name=title::Patch"
          elif [ -n "$MINOR" ]; then
            echo "::set-output name=title::Minor"
          elif [ -n "$MAJOR" ]; then
            echo "::set-output name=title::Major"
          else
            echo "::set-output name=title::Patch"
          fi

      - name: Set Merge Commit Title
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --subject "${{ steps.check-template.outputs.title }}" --body "Merged by GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
