name: Merge Title Enforcer

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  enforce-merge-title:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'stg'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Determine Merge Title
        id: determine-title
        run: |
          echo "Getting PR details"
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)

          if [[ "$PR_BODY" == *"- [x] Patch"* ]]; then
            echo "::set-output name=title::Patch"
          elif [[ "$PR_BODY" == *"- [x] Minor"* ]]; then
            echo "::set-output name=title::Minor"
          elif [[ "$PR_BODY" == *"- [x] Major"* ]]; then
            echo "::set-output name=title::Major"
          else
            echo "::set-output name=title::Patch"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Merge Commit Title
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --subject "${{ steps.determine-title.outputs.title }}" --body "Merged by GitHub Actions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
