name: PR Title Enforcer

on:
  pull_request:
    branches:
      - main
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.1'

      - name: Determine PR Title
        id: determine-title
        run: |
          echo "Getting PR details"
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)

          if [[ "$PR_BODY" == *"- [x] Patch"* ]]; then
            echo "::set-output name=title::🔖 Release:patch"
          elif [[ "$PR_BODY" == *"- [x] Minor"* ]]; then
            echo "::set-output name=title::🔖 Release:minor"
          elif [[ "$PR_BODY" == *"- [x] Major"* ]]; then
            echo "::set-output name=title::🔖 Release:major"
          else
            echo "::set-output name=title::🔖 Release:patch"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR Title
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --title "${{ steps.determine-title.outputs.title }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
