name: main

on:
  pull_request:
    branches:
      - main
    types: [ opened, edited ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  title:
    name: title
    uses: ./.github/workflows/main-title.yml
    secrets: inherit

  labeler:
    name: labeler
    needs: title
    uses: ./.github/workflows/main-labeling.yml
    secrets: inherit
