name: release

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The number of the PR to label'
        required: true

# on:
#   pull_request:
#     branches:
#       - 'main'
#     types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL }}